debian/dh_girepository /usr/bin
debian/deb-elf-get-needed /usr/libexec/gobject-introspection-bin
debian/gir.pm /usr/share/perl5/Debian/Debhelper/Sequence
usr/bin/g-ir-*
usr/lib/${DEB_HOST_MULTIARCH}/gobject-introspection/giscanner/*.py
usr/lib/${DEB_HOST_MULTIARCH}/gobject-introspection/giscanner/*.so
usr/lib/${DEB_HOST_MULTIARCH}/gobject-introspection/giscanner/doctemplates
usr/share/aclocal
usr/share/gir-${env:GIR_API_VERSION}/gir-1.2.rnc
usr/share/gobject-introspection-${env:GIR_API_VERSION}
usr/share/man
